APP_NAME = "SprintDash"

STATUS_IDLE = "IDLE"
STATUS_READY = "READY"
STATUS_ARMED = "ARMED"
STATUS_RUNNING = "RUNNING"
STATUS_STOPPED = "STOPPED"
STATUS_FINISHED = "FINISHED"
STATUS_NEED_LOCATION = "NEED_LOCATION"

STATUS_LABELS = {
    STATUS_IDLE: "Siap",
    STATUS_READY: "GPS Ready",
    STATUS_ARMED: "Armed",
    STATUS_RUNNING: "Running",
    STATUS_STOPPED: "Stop Manual",
    STATUS_FINISHED: "Selesai",
    STATUS_NEED_LOCATION: "Ambil lokasi dulu",
}

FT_PER_M = 3.28084
DEFAULT_TARGET = 201.0
MIN_TARGET = 1.0
MAX_TARGET = 100000.0
MOVEMENT_THRESHOLD_M = 1.5
MIN_ACCURACY_M = 50.0
